# required imports

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

# next line is the project description, format is #(tilde){name}|{desc}|{ver}
#~helloworld!|AOS-GUI Demo App|v1.0


class hiworld(QWidget):

    # this can be your normal PyQt5 code, go crazy!
    def __init__(self):
        super(hiworld, self).__init__()
        self.setFixedSize(400, 300)
        self.setWindowTitle("Hello, World!")
        self.setWindowFlags(Qt.Window | Qt.WindowStaysOnTopHint)

        self.label = QLabel(self)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 128, 400, 31))
        self.label.setText(u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">HELLO, WORLD!</span></p></body></html>")
        self.pushButton = QPushButton(self)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 0, 75, 23))
        self.pushButton.setText(u"PushButton")
        self.toolButton = QToolButton(self)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(80, 0, 25, 19))
        self.toolButton.setText(u"...")
        self.radioButton = QRadioButton(self)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(110, 0, 82, 17))
        self.radioButton.setText(u"")
        self.checkBox = QCheckBox(self)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(130, 0, 70, 17))
        self.commandLinkButton = QCommandLinkButton(self)
        self.commandLinkButton.setObjectName(u"commandLinkButton")
        self.commandLinkButton.setGeometry(QRect(150, -10, 185, 31))
        self.commandLinkButton.setText(u"")
        self.buttonBox = QDialogButtonBox(self)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(240, 0, 156, 23))
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.comboBox = QComboBox(self)
        self.comboBox.addItem(u"Hello")
        self.comboBox.addItem(u"World!")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(0, 20, 69, 22))
        self.comboBox.setCurrentText(u"Hello")
        self.fontComboBox = QFontComboBox(self)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setGeometry(QRect(70, 20, 91, 22))
        self.lineEdit = QLineEdit(self)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(160, 20, 61, 20))
        self.textEdit = QTextEdit(self)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(220, 20, 104, 21))
        self.spinBox = QSpinBox(self)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(330, 20, 61, 22))
        self.doubleSpinBox = QDoubleSpinBox(self)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(0, 40, 62, 22))
        self.timeEdit = QTimeEdit(self)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(70, 40, 71, 22))
        self.dateEdit = QDateEdit(self)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(140, 40, 71, 22))
        self.dateTimeEdit = QDateTimeEdit(self)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(210, 40, 194, 22))
        self.dial = QDial(self)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(0, 60, 50, 64))
        self.horizontalScrollBar = QScrollBar(self)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setGeometry(QRect(50, 70, 160, 16))
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.horizontalSlider = QSlider(self)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(60, 90, 160, 22))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.verticalScrollBar = QScrollBar(self)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setGeometry(QRect(380, 70, 16, 221))
        self.verticalScrollBar.setOrientation(Qt.Vertical)
        self.verticalSlider = QSlider(self)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(350, 70, 22, 221))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.keySequenceEdit = QKeySequenceEdit(self)
        self.keySequenceEdit.setObjectName(u"keySequenceEdit")
        self.keySequenceEdit.setGeometry(QRect(230, 70, 113, 20))
        self.textBrowser = QTextBrowser(self)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 120, 101, 81))
        self.textBrowser.setHtml("<h1>AOS-GUI</h1>")
        self.calendarWidget = QCalendarWidget(self)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(0, 210, 341, 91))
        self.lcdNumber = QLCDNumber(self)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(230, 90, 121, 31))
        self.lcdNumber.setDigitCount(6)
        self.lcdNumber.setMode(QLCDNumber.Hex)
        self.lcdNumber.setProperty("value", 48879)
        self.lcdNumber.setProperty("intValue", 48879)
        self.progressBar = QProgressBar(self)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(110, 170, 241, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setValue(88)

# these last two lines must be included for the app to launch.

window = hiworld()
window.show()
